name: "terrier"
#not tuned yet
start_throttle: 95
stop_throttle: 90
cruise_throttle: 120

images:
  front: "images/terrier_front.png"
  side: "images/terrier_side.png"
  top: "images/terrier_top.png"

sounds:
  SND_ACCELERATE:
    duration: 42
    path: "terrier/terrier_station_start_steam_hiss_exhaust_beat_pass_diesel_gen.flac"

  SND_DECELERATE:
    duration: 18
    path: "terrier/terrier_arrival_hiss_brake_squeak_talking.flac"

  SND_SHORT_WHISTLE:
    duration: 16
    path: "terrier_short_whistle_brake_hiss_steam_hiss_talking_background.flac"

  SND_LONG_WHISTLE:
    duration: 11
    path: "terrier/terrier_long_whistle.flac"

  SND_PASS_MED:
    duration: 49
    path: "terrier/terrier_approach_pass_and_coach_clicketyclack3.flac"
